config/routes.rb
Rails.application.routes.draw do

  root 'application#index'

  resources :carrierwaves
  resources :paperclip_models
  resources :dragonfly_models

end

app/models/carrierwave.rb
class Carrierwave
  include Mongoid::Document
  include Mongoid::Attributes::Dynamic
  mount_uploader :file, FileUploader, mount_on: :file_filename
  mount_uploader :image, ImageUploader, mount_on: :image_filename
end

app/models/dragonfly_model.rb
class DragonflyModel
  include Mongoid::Document
  include Mongoid::Attributes::Dynamic
end

app/models/paperclip_model.rb
class PaperclipModel
  include Mongoid::Document
  include Mongoid::Attributes::Dynamic
  include Mongoid::Paperclip

  #### IMAGE
  has_mongoid_attached_file :image,
    # :path           => "#{Rails.root}/public/uploads/paperclip_image/:attachment/:id/:style.:extension",
    # :storage        => :s3,
    # :url            => ':s3_alias_url',
    # :s3_host_alias  => 'something.cloudfront.net',
    # :s3_credentials => File.join(Rails.root, 'config', 's3.yml'),
    :styles => {
      :original => ['1920x1680>', :jpg], # thumbnail will only be modified if it is currently larger requested dimensions
      :small    => ['50x50#',   :jpg], # thumbnail will be centrally cropped, ensuring 100x100 dimensions & save to jpg
      :medium   => ['250x250',    :jpg], # thumbnail will be resized to requested dimensions
      :large    => ['500x500>',   :jpg]  # thumbnail will only be modified if it is currently larger requested dimensions
    },
    :convert_options => { :all => '-background white -flatten +matte -quality 75 -strip', small: '-rotate 90' }

  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  
  validates_attachment_presence :image


  #### FILE
  has_mongoid_attached_file :file
  validates_attachment_presence :file
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/carrierwaves_controller.rb
class CarrierwavesController < ApplicationController
  # attr_accessible :file, :file_cache
  # attr_accessible :image, :image_cache
  def index
    @carrierwave_models = Carrierwave.page params[:page]
  end

  def create
    carrierwave = Carrierwave.new carrierwave_params
    if carrierwave.save
      redirect_to root_path, notice: 'Carrierwave created'
    else
      redirect_to root_path, notice: 'something wrong creating carrierwave'
    end
  end

  private
    def carrierwave_params
      params.require(:carrierwave).permit(:image, :file)
    end
end

app/controllers/dragonfly_models_controller.rb
class DragonflyModelsController < ApplicationController

  def create
    dragonfly_model = DragonflyModel.new dragonfly_model_params
    if dragonfly_model.save
      redirect_to root_path, notice: 'dragonfly_model created'
    else
      redirect_to root_path, notice: 'something wrong creating dragonfly_model'
    end
  end

  private
    def dragonfly_model_params
      params.require(:dragonfly_model).permit(:image, :file)
    end

end

app/controllers/paperclip_models_controller.rb
class PaperclipModelsController < ApplicationController
  
  def index
    @paperclip_models = PaperclipModel.page params[:page]
  end

  def create
    paperclip_model = PaperclipModel.new paperclip_model_params
    if paperclip_model.save
      redirect_to root_path, notice: 'paperclip_model created'
    else
      redirect_to root_path, notice: 'something wrong creating paperclip_model'
    end
  end

  private
    def paperclip_model_params
      params.require(:paperclip_model).permit(:image, :file)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/index.html.haml
%h1
  Codetails 24-11-15
  %small
    Daniel Romero Esteban
%h5
  Carrierwave vs Paperclip vs Dragonfly sobre MongoId
.collection
  =link_to(carrierwaves_path,class: 'collection-item') do
    Carrierwave
    %span.badge=Carrierwave.count
  
  =link_to(paperclip_models_path,class: 'collection-item') do
    Paperclip
    %span.badge=PaperclipModel.count

  =link_to(dragonfly_models_path,class: 'collection-item') do
    Dragonfly
    %span.badge=DragonflyModel.count

app/views/carrierwaves/_form.html.haml
= form_for Carrierwave.new, html: { multipart: true } do |f|
  .file-field.input-field
    .btn.waves-effect.waves-light
      %span File
      = f.file_field :file
    .file-path-wrapper
      <input class="file-path validate" type="text">
  .file-field.input-field
    .btn.waves-effect.waves-light
      %span Image
      = f.file_field :image
    .file-path-wrapper
      <input class="file-path validate" type="text">
  =f.submit 'Pa subir', class: 'btn right'

app/views/carrierwaves/index.html.haml
%h2.col.s12.header Carrierwave
=render partial: 'form'


%hr{style: 'margin: 100px 0px;'}
-@carrierwave_models.each do |carrierwave|
  -# IMAGE
  %table
    %thead
      %tr
        %th="1920x1680>"
        %th="500x500>"
        %th="250x250"
        %th="100x100#"
    %tbody
      %tr
        %td= image_tag carrierwave.image.original.url
        %td= image_tag carrierwave.image.large.url
        %td= image_tag carrierwave.image.medium.url
        %td= image_tag carrierwave.image.small.url
  -# FILE
  %table
    %thead
      %tr
        %th Name
        %th URL
        
    %tbody
      %tr
        %td= image_tag carrierwave.file.url
        %td= link_to 'download', carrierwave.file.url, target: 'blank'
        
  %hr{style: 'margin-top: 100px;'}
  %hr{style: 'margin-bottom: 100px;'}
= paginate @carrierwave_models

app/views/dragonfly_models/_form.html.haml
= form_for DragonflyModel.new, html: { multipart: true } do |f|
  %p
    %label File
    = f.file_field :image
  =f.submit

app/views/dragonfly_models/index.html.haml
%h2.col.s12.header Dragonfly
=render partial: 'form'

app/views/layouts/_header.html.haml
%nav{:role => "navigation"}
  .nav-wrapper.container
    %ul#nav-mobile.left.hide-on-med-and-down
      %li
        =link_to root_path do
          Codetails

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Codetails
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true

    %link{:href => "http://fonts.googleapis.com/icon?family=Material+Icons", :rel => "stylesheet"}/
    %link{:href => "https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/css/materialize.min.css", :rel => "stylesheet"}
    %script{:src => "https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/js/materialize.min.js"}
    
    = csrf_meta_tags
  %body
    =render partial: 'layouts/header'
    .container
      %p= flash[:notice]
      = yield

app/views/paperclip_models/_form.html.haml
= form_for PaperclipModel.new, html: { multipart: true } do |f|
  .file-field.input-field
    .btn.waves-effect.waves-light
      %span File
      = f.file_field :file
    .file-path-wrapper
      <input class="file-path validate" type="text">
  .file-field.input-field
    .btn.waves-effect.waves-light
      %span Image
      = f.file_field :image
    .file-path-wrapper
      <input class="file-path validate" type="text">
  =f.submit 'Pa subir', class: 'btn right'

app/views/paperclip_models/index.html.haml
%h2.col.s12.header Paperclip
=render partial: 'form'
.clearfix

%hr{style: 'margin: 100px 0px;'}
-@paperclip_models.each do |paperclip_model|
  -# IMAGE
  %table
    %thead
      %tr
        %th="1920x1680>"
        %th="500x500>"
        %th="250x250"
        %th="100x100#"
    %tbody
      %tr
        %td= image_tag paperclip_model.image.url(:original)
        %td= image_tag paperclip_model.image.url(:large)
        %td= image_tag paperclip_model.image.url(:medium)
        %td= image_tag paperclip_model.image.url(:small)
  -# FILE
  %table
    %thead
      %tr
        %th Name
        %th URL
        
    %tbody
      %tr
        %td= image_tag paperclip_model.file.url(:thumb)
        %td= link_to 'download', paperclip_model.file.url, target: 'blank'
        
  %hr{style: 'margin-top: 100px;'}
  %hr{style: 'margin-bottom: 100px;'}
= paginate @paperclip_models